import { wrapFunctional } from './utils'

export const SComment = import('../..\\components\\SComment.vue' /* webpackChunkName: "components/s-comment" */).then(c => wrapFunctional(c.default || c))
export const SDialog = import('../..\\components\\SDialog.vue' /* webpackChunkName: "components/s-dialog" */).then(c => wrapFunctional(c.default || c))
export const TheAPlayer = import('../..\\components\\TheAPlayer.vue' /* webpackChunkName: "components/the-a-player" */).then(c => wrapFunctional(c.default || c))
export const TheArchives = import('../..\\components\\TheArchives.vue' /* webpackChunkName: "components/the-archives" */).then(c => wrapFunctional(c.default || c))
export const TheBackTop = import('../..\\components\\TheBackTop.vue' /* webpackChunkName: "components/the-back-top" */).then(c => wrapFunctional(c.default || c))
export const TheFooter = import('../..\\components\\TheFooter.vue' /* webpackChunkName: "components/the-footer" */).then(c => wrapFunctional(c.default || c))
export const TheInfoCard = import('../..\\components\\TheInfoCard.vue' /* webpackChunkName: "components/the-info-card" */).then(c => wrapFunctional(c.default || c))
export const TheLive2d = import('../..\\components\\TheLive2d.vue' /* webpackChunkName: "components/the-live2d" */).then(c => wrapFunctional(c.default || c))
export const TheLive2dTools = import('../..\\components\\TheLive2dTools.vue' /* webpackChunkName: "components/the-live2d-tools" */).then(c => wrapFunctional(c.default || c))
export const TheNav = import('../..\\components\\TheNav.vue' /* webpackChunkName: "components/the-nav" */).then(c => wrapFunctional(c.default || c))
export const SChip = import('../..\\components\\SChip\\index.vue' /* webpackChunkName: "components/s-chip" */).then(c => wrapFunctional(c.default || c))
export const SMarkdown = import('../..\\components\\SMarkdown\\index.vue' /* webpackChunkName: "components/s-markdown" */).then(c => wrapFunctional(c.default || c))
export const SLabelClouds = import('../..\\components\\SLabelClouds\\index.vue' /* webpackChunkName: "components/s-label-clouds" */).then(c => wrapFunctional(c.default || c))
export const SPagination = import('../..\\components\\SPagination\\index.vue' /* webpackChunkName: "components/s-pagination" */).then(c => wrapFunctional(c.default || c))
export const TheBanner = import('../..\\components\\TheBanner\\index.vue' /* webpackChunkName: "components/the-banner" */).then(c => wrapFunctional(c.default || c))
export const SPostItem = import('../..\\components\\SPostItem\\SPostItem.vue' /* webpackChunkName: "components/s-post-item" */).then(c => wrapFunctional(c.default || c))
